#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
"""The REAC protocol's numbers, from their ONE declaration.

The declaration is reac-protocol's spec/protocol-facts.yaml, turned into
spec/generated/reac_facts.h by spec/gen-facts.py. reac-pw never declares a
protocol number itself; it reads that header. The operator's ruling
(2026-09-25): "declare only once and use it everywhere - a single source of
truth; hardcoded constants are the worst practice and a source of nasty bugs".

THE MECHANISM IS libreac's facts-drift-check, not a second one. A verbatim copy
of the generated header is committed as facts/reac_facts.h, so a standalone
build and an RPM build need no reac-protocol checkout. When one IS reachable,
`drift` regenerates the header with reac-protocol's own generator and requires
the committed copy to be byte-identical. A stale copy fails there instead of
building quietly.

    facts.py undef FACTS_H OUT       write reac_facts_undef.h for FACTS_H
    facts.py drift REAC_PROTOCOL     the drift gate (exit 77 when unreachable)
    facts.py perturb REAC_PROTOCOL SEED OUTDIR
                                     a consistent FICTIONAL fact set, for
                                     tools/facts-perturb-check.sh
    facts.py get NAME [NAME...]      print values (for shell scripts)
    facts.py env                     export FACT_<NAME>=<value> lines (tests/facts.sh)

Python tools import this module: `from facts import FACTS` gives
{"ETHERTYPE": 0x8819, ...}, read from $REACPW_FACTS_DIR/reac_facts.h when the
perturbation check sets it, and from the committed copy otherwise.
"""
import difflib
import os
import pathlib
import re
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent.parent
VENDORED = HERE / "facts"
SKIP = 77

DEFINE = re.compile(r"^#define REAC_([A-Z0-9_]+)\s+(\S.*?)\s*(?:/\*.*)?$", re.M)


def names_of(text):
    return [m.group(1) for m in DEFINE.finditer(text)]


def parse(text):
    """{NAME: int} for every scalar fact (tables are skipped)."""
    out = {}
    for name, val in DEFINE.findall(text):
        val = val.strip()
        try:
            out[name] = int(val, 0)
        except ValueError:
            pass
    return out


def facts_dir():
    return pathlib.Path(os.environ.get("REACPW_FACTS_DIR") or VENDORED)


def load():
    return parse((facts_dir() / "reac_facts.h").read_text())


# THE UNDEF HEADER. libreac's public headers still define about fifty of these
# names by hand (the migration libreac's test_facts.c describes), several spelled
# differently (0xC2 vs 0xc2, 0x0600u vs 0x0600). reac_facts_pw.h includes those
# headers first, then this file, then reac_facts.h, so the generated definition
# is the one reac-pw compiles against and no redefinition is ever diagnosed. It
# is derived from the header by name, so it cannot fall behind it.
def emit_undef(facts_text):
    lines = ["// GENERATED by tools/facts.py undef from reac_facts.h - DO NOT EDIT.",
             "// Clears libreac's hand copies of these names before reac_facts.h",
             "// defines them (see src/reac_facts_pw.h).",
             "#ifndef REACPW_FACTS_UNDEF_H", "#define REACPW_FACTS_UNDEF_H"]
    lines += [f"#undef REAC_{n}" for n in names_of(facts_text)]
    lines += ["#endif", ""]
    return "\n".join(lines)


def gen_facts(rp, *extra):
    gen = pathlib.Path(rp) / "spec" / "gen-facts.py"
    return subprocess.run([sys.executable, str(gen), *extra],
                          capture_output=True, text=True)


def reachable(rp):
    spec = pathlib.Path(rp) / "spec"
    if not (spec / "gen-facts.py").is_file() or not (spec / "protocol-facts.yaml").is_file():
        return False
    try:
        import yaml  # noqa: F401  (gen-facts.py needs it)
    except ImportError:
        return False
    return True


def cmd_drift(rp):
    if not reachable(rp):
        print(f"SKIP: reac-protocol not reachable at {rp} (or no python3-yaml); "
              "building against the committed facts/reac_facts.h")
        return SKIP
    with tempfile.TemporaryDirectory() as tmp:
        r = gen_facts(rp, "--outdir", tmp)
        if r.returncode != 0:
            print(r.stdout + r.stderr)
            print("FAIL: reac-protocol's gen-facts.py could not generate")
            return 1
        fresh = (pathlib.Path(tmp) / "reac_facts.h").read_text()
    bad = 0
    for name, want in (("reac_facts.h", fresh), ("reac_facts_undef.h", emit_undef(fresh))):
        have = (VENDORED / name).read_text()
        if have != want:
            sys.stdout.writelines(difflib.unified_diff(
                have.splitlines(True), want.splitlines(True),
                f"facts/{name}", f"regenerated from {rp}"))
            print(f"FAIL: facts/{name} has drifted from {rp}/spec/protocol-facts.yaml.")
            print(f"      Refresh: tools/facts.py refresh {rp}")
            bad = 1
    if not bad:
        print(f"OK: facts/ is byte-identical to what {rp} generates "
              f"({len(names_of(fresh))} facts)")
    return bad


def cmd_refresh(rp):
    if not reachable(rp):
        print(f"FAIL: reac-protocol not reachable at {rp}")
        return 1
    with tempfile.TemporaryDirectory() as tmp:
        r = gen_facts(rp, "--outdir", tmp)
        if r.returncode != 0:
            print(r.stdout + r.stderr)
            return 1
        fresh = (pathlib.Path(tmp) / "reac_facts.h").read_text()
    VENDORED.mkdir(exist_ok=True)
    (VENDORED / "reac_facts.h").write_text(fresh)
    (VENDORED / "reac_facts_undef.h").write_text(emit_undef(fresh))
    print(f"refreshed facts/ from {rp}")
    return 0


def cmd_perturb(rp, seed, outdir):
    if not reachable(rp):
        print(f"FAIL: reac-protocol not reachable at {rp}")
        return 1
    out = pathlib.Path(outdir)
    r = gen_facts(rp, "--perturb", str(seed), "--outdir", str(out))
    if r.returncode != 0:
        print(r.stdout + r.stderr)
        return 1
    (out / "reac_facts_undef.h").write_text(emit_undef((out / "reac_facts.h").read_text()))
    return 0


def main(argv):
    if len(argv) >= 3 and argv[0] == "undef":
        pathlib.Path(argv[2]).write_text(emit_undef(pathlib.Path(argv[1]).read_text()))
        return 0
    if len(argv) == 2 and argv[0] == "drift":
        return cmd_drift(argv[1])
    if len(argv) == 2 and argv[0] == "refresh":
        return cmd_refresh(argv[1])
    if len(argv) == 4 and argv[0] == "perturb":
        return cmd_perturb(argv[1], argv[2], argv[3])
    if len(argv) == 1 and argv[0] == "env":
        # For shell: `eval "$(tools/facts.py env)"` exports FACT_<NAME>=<value>. The
        # FACT_ prefix is deliberate: the daemon reads REAC_* / REACPW_* knobs, and an
        # exported fact must never be mistaken for one.
        for k, v in sorted(load().items()):
            print(f"export FACT_{k}={v}")
        return 0
    if len(argv) >= 2 and argv[0] == "get":
        f = load()
        for n in argv[1:]:
            print(f[n.removeprefix("REAC_")])
        return 0
    print(__doc__)
    return 2


FACTS = load() if __name__ != "__main__" else None

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
