#!/usr/bin/env python3
"""Emit src/reac_scene_body.c from a recovered scene body.

    tools/gen-scene-body.py data/m200i-scene-8904.bin > src/reac_scene_body.c

The body must be exactly 8904 bytes — the total the op-0101 header declares and
the box checks its reassembly against. Anything else is a truncated or decimated
recovery (tools/recover-scene.py) and is refused here rather than compiled in.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from facts import FACTS   # the protocol's numbers, from their one declaration (tools/facts.py)

body = open(sys.argv[1], 'rb').read()
if len(body) != FACTS["SCENE_BYTES"]:
    sys.exit(f'REFUSED: {len(body)} bytes, not {FACTS["SCENE_BYTES"]}')

print('// SPDX-License-Identifier: GPL-3.0-or-later')
print('// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>')
print('//')
print('// GENERATED by tools/gen-scene-body.py — do not edit by hand.')
print('//')
print('// A PROTOCOL PLACEHOLDER, not our console\'s scene. These are a real M-200i\'s')
print('// bytes, recovered with tools/recover-scene.py from')
print('//   m200i-s1608-48k-mirror__real-m200-s1608-coldboot-2026-07-11.pcap')
print('// and kept because a body of the RIGHT LENGTH is what lets the transfer')
print('// complete and the box run its commit. The scene is the mixer\'s state, so')
print('// generating this from our own console is the follow-on work; the framing')
print('// itself lives in libreac (reac_ctrlblk.c) and had to be right first.')
print()
print('#include "reac_scene_body.h"')
print()
print('const uint8_t reac_scene_placeholder[REAC_SCENE_BYTES] = {')
for i in range(0, len(body), 12):
    row = ', '.join(f'0x{b:02x}' for b in body[i:i + 12])
    print(f'\t{row},')
print('};')
