/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com> */

/* reac_declared_vlan — the VLAN segments the OPERATOR declared, as opposed to the ones
 * the wire happened to mention.
 *
 * THE FAULT THIS EXISTS FOR, MEASURED 2026-09-15 ON THE DESK. reac_topo mints
 * `<parent>.<vid>` when it HEARS a tagged REAC frame on the trunk, which is the right
 * rule for discovery and the wrong one for a cold boot: a stagebox is a SLAVE, it says
 * nothing until a master speaks, and the master cannot speak until its segment's netdev
 * exists. Nothing is heard, so nothing is minted, so nothing can be heard. After the
 * reboot every declared segment was dead and every box unenrolled, with no error
 * anywhere — the daemon was behaving exactly as written.
 *
 * A DECLARATION IS NOT A DISCOVERY, AND IT DOES NOT WAIT FOR ONE. `REAC_ROLE_enp131s0.11`
 * in the config, or an `enp131s0.11.env` beside it, says THIS SEGMENT EXISTS. It is the
 * operator's statement about the installation, and the daemon's job is to make the host
 * match it — the same rule reac_qdisc.h states for the qdisc and the same one that says a
 * drop-in is generated by the app that owns it. So a declared VLAN is minted at start and
 * whenever its parent appears, whether or not anything has ever been heard on it.
 *
 * TWO LEDGERS, ON PURPOSE, BECAUSE THEY HAVE DIFFERENT LIFETIMES. reac_topo owns what it
 * HEARD and releases a VID that has been silent for 30 s — correct for a box unplugged
 * from a trunk, and fatal for a declared segment on a cold rig, where silence is the
 * starting condition. So the declared set is kept here and the heard table is told those
 * netdevs are ADOPTED (`minted = 0`), which is precisely the flag that makes reac_topo
 * leave them alone. The exit still removes exactly what was minted, from this side.
 *
 * WHAT COUNTS AS A DECLARATION. Any configuration key naming a segment whose name splits
 * as `<parent>.<vid>`, in any layer reac_conf reads (the process environment,
 * `~/.config/reac-pw/reac-pw.env`, `~/.config/openmixer/reac.env`), plus the presence of a
 * per-segment `~/.config/reac-pw/<parent>.<vid>.env` file. The VALUE is not read and does
 * not matter: naming the segment at all is the declaration, so a segment declared only by
 * a rate or a name is minted like one declared by a role.
 *
 * THE SEGMENT IS THE TEXT AFTER THE LAST UNDERSCORE, which is how reac_conf's own
 * `<KEY>_<segment>` suffix works in every key it reads. A parent whose interface name
 * CONTAINS an underscore therefore cannot be declared this way — no predictable name
 * (enp*, eno*, eth*, ens*) has one, and the `.env` filename source has no such limit. */
#ifndef REAC_DECLARED_VLAN_H
#define REAC_DECLARED_VLAN_H

#include <net/if.h>
#include <stddef.h>
#include <stdint.h>

/* Two trunks' worth at reac_topo's own per-parent bound. Anything past it is REPORTED by
 * the caller, never silently dropped. */
#define REAC_DECLARED_VLAN_MAX 32

struct reac_declared_vlan {
	char     parent[IFNAMSIZ];
	uint16_t vid;
};

/* Split a segment name into parent and VID at its LAST dot. Returns 1 when it is a VLAN
 * segment, 0 when it is not (no dot, a non-numeric or out-of-range tail, an empty parent,
 * a name that would not fit). A VID is 1..4094: 0 is the priority tag and 4095 is
 * reserved, and neither names a netdev anyone can create. */
int reac_declared_vlan_split(const char *segment, char *parent, size_t cap, uint16_t *vid);

/* The same, from a configuration KEY (`REAC_ROLE_enp131s0.11`). The key must begin with
 * "REAC"; the segment is what follows its last underscore. Returns 1/0 as above. */
int reac_declared_vlan_from_key(const char *key, char *parent, size_t cap, uint16_t *vid);

/* The same, from a per-segment file NAME (`enp131s0.11.env`; a path is accepted and its
 * directory ignored). Returns 1/0 as above — `reac-pw.env` and `enp131s0.env` are 0. */
int reac_declared_vlan_from_filename(const char *fname, char *parent, size_t cap,
                                     uint16_t *vid);

/* Add (parent, vid) to `tab` if it is not already there. Returns 1 added, 0 duplicate,
 * -1 table full. `*n` is the live count and is advanced on an add. */
int reac_declared_vlan_add(struct reac_declared_vlan *tab, int max, int *n,
                           const char *parent, uint16_t vid);

/* Scan one KEY=VALUE text block (a conf file's whole contents) for declaring keys. Only
 * the key NAMES are read; values, comments and blank lines are ignored. Returns how many
 * NEW entries were added, or -1 if the table filled before the text ran out. */
int reac_declared_vlan_scan_text(const char *text, struct reac_declared_vlan *tab, int max,
                                 int *n);

/* Every declaration this host carries: the process environment, then the two conf files,
 * then the per-segment filenames in `~/.config/reac-pw/`. `home` NULL means $HOME, the
 * same convention reac_conf_lookup uses. Returns the number of segments found, or -1 when
 * the table filled (the entries found before that are still there, and the caller says
 * so — a bound that is silently hit is a bound nobody can act on). */
int reac_declared_vlan_scan(struct reac_declared_vlan *tab, int max, const char *home);

#endif /* REAC_DECLARED_VLAN_H */
