// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>

#include "reac_master.h"
#include "reac_ctrl.h"   /* reac_ctrl_checksum_apply, REAC_CTRL_* offsets */
#include "reac_grant.h"  /* the generated enrollment sweep + slot allocator */

#include <reac/reac.h>   /* REAC_FRAME_BYTES, REAC_END_MARKER_*, ... */
#include <stdlib.h>      /* getenv (REACPW_ANNOUNCE_UNGRANTED A/B toggle) */
#include <string.h>

/* ------------------------------------------------------------------------- *
 * The downstream control plane: three FIXED protocol constants + two GENERATED
 * blocks (byte source-of-truth: reac-captures/m300-s1608-*.pcap, 2026-07-10,
 * real M-300 master 00:40:ab:c9:d8:5b driving an S-1608).
 *
 * A real master CONTINUOUSLY advertises five control messages; each is 34 bytes
 * [16:50] = the 2 type bytes (cd ea / cf ea) + the 32-byte control block
 * [18:50], with Sum(block[18..49]) mod 256 == 0.
 *
 *   PROBE / SUB01 / SUB02 — cdea 01 00 / 01 01 / 01 02. FIXED protocol
 *       constants replayed verbatim: the M-300 capture is the only source for
 *       them, so no config vs constant split is provable. (SUB01 carries an
 *       ASCII "1234" token at block bytes [7:11] that may be a per-unit id;
 *       for the S-1608 replay the box is bound to THIS master identity so the
 *       captured token is correct. Flagged in the task's openMitigations.)
 *   CHANMAP — cdea 01 03 0019: the 11-window SWEEP a real master advertises to
 *       tile the whole 40-slot fabric 0x00..0x2f (gen_chanmap), byte-faithful to
 *       the captured M-300 establish sweep. A box enrolls ONLY after it sees the
 *       window mapping ITS OWN slots, so the map is fabric-wide, not console-
 *       width (fixing #130: the old one-frame 0x00..0x06 map left every box mute).
 *   CFEA (announce) — cfea: GENERATED from the console cfg + OUR src MAC
 *       (gen_cfea): fixed head + our MAC + inCh 0x28(=40) + outCh + the console
 *       field, checksummed. On-wire identity must equal the L2 source, so the
 *       MAC is always OURS (never a cloned desk MAC — a slave-disconnect
 *       trigger). Fed the S-1608 cfg with the M-300 MAC it is byte-exact.
 *
 *   GRANT — cdea 04 03: the per-channel ENROLLMENT SWEEP, GENERATED by
 *       reac_grant.c from the fabric slots WE allocate to the connected box
 *       (m->alloc) and our own head-amp state. NOT a canned block and NOT a
 *       replayed table: see reac_grant.h for why (group A is the head-amp state
 *       push, so a sweep that enrolls the wrong slots silently voids every later
 *       head-amp record — the 2026-07-17 "48V never lights" failure).
 *       reac_master_set_box re-allocates + rebuilds it on box recognition.
 * ------------------------------------------------------------------------- */

/* The two fixed M-300 control constants (byte-exact, checksum-valid). The PROBE is
 * NOT a constant — it rotates; see gen_probe(). */
static const uint8_t SUB01_BLK[34] = { 0xcd, 0xea, 0x01, 0x01, 0x00, 0x18, 0x00, 0x22, 0xc8, 0x31, 0x32, 0x33, 0x34, 0x01, 0x00, 0x00, 0x00, 0x04, 0x00, 0x01, 0x80, 0x02, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0xa7 };
static const uint8_t SUB02_BLK[34] = { 0xcd, 0xea, 0x01, 0x02, 0x00, 0x0e, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0xe7 };

/* The cfea master-MAC field sits at template idx 11..16 (block [9:15]). */
#define ANNOUNCE_MAC_IDX 11

/* Set blk[33] so the 32-byte control block [2:34] sums to 0 mod 256 (the
 * cdea/cfea checksum rule; identical to reac_ctrl_checksum_apply on a frame). */
static void stamp_block_cksum(uint8_t blk[34])
{
	unsigned s = 0;
	for (int i = 2; i < 33; i++)   /* block bytes [18:49] = template [2:33] */
		s += blk[i];
	blk[33] = (uint8_t)((256 - (s & 0xff)) & 0xff);
}

/* ---- PROBE: the rotating hunt sequence (#130) -----------------------------
 * Measured live off an M-200 driving an S-1608 (2026-07-11): the cdea 01 00 001a
 * probe's 27-byte payload is a sliding window over the period-10 sequence
 *   [ 00 00 00 01 00 00 00 00 00 SUB ]
 * with SUB = 0x02 while hunting, 0x03 once established. The phase advances +6
 * (mod 10) after every 2 emissions, yielding the observed 0,6,2,8,4 rotation.
 * All 10 rotating probe blocks in the capture reproduce exactly under this model.
 * Our old code replayed ONE frozen phase (6/0x02, checksum 0xdd) forever. */
#define REAC_PROBE_PERIOD     10
#define REAC_PROBE_PHASE_STEP  6   /* phase += 6 (mod 10) -> 0,6,2,8,4 */
#define REAC_PROBE_REPEAT      2   /* emissions per phase before advancing */
#define REAC_PROBE_PAYLOAD    27   /* block[4:31] */

static void gen_probe(uint8_t blk[34], int phase, uint8_t sub)
{
	const uint8_t per[REAC_PROBE_PERIOD] = { 0, 0, 0, 1, 0, 0, 0, 0, 0, sub };
	memset(blk, 0, 34);
	blk[0] = 0xcd; blk[1] = 0xea;
	blk[2] = 0x01; blk[3] = 0x00;   /* cdea 01 00      */
	blk[4] = 0x00; blk[5] = 0x1a;   /* BE len 0x001a   */
	for (int i = 0; i < REAC_PROBE_PAYLOAD; i++)
		blk[6 + i] = per[(phase + i) % REAC_PROBE_PERIOD];
	stamp_block_cksum(blk);         /* -> blk[33] */
}

/* The 4 INVENTORY SPECIALS (#130): every probe burst carries, at in-burst probe
 * indices 30..33, four one-off probe variants — measured on the M-300/S-1608
 * establish capture at exactly those indices in EVERY burst (11/11), and present
 * in the M-200 corpora too. Bytes verbatim from the M-300 (checksum-valid); the
 * MAC special embeds the master's OWN MAC at block[7:13] (template [9:15]) — we
 * substitute OURS and re-checksum. A master that never sends these is another
 * tell of a dead downstream. */
#define REAC_PROBE_SPECIAL_FIRST 30
#define REAC_PROBE_SPECIAL_COUNT  4
#define PROBE_SPECIAL_MAC_IDX     9   /* template idx of the 6-byte MAC */
static const uint8_t PROBE_SPECIALS[REAC_PROBE_SPECIAL_COUNT][34] = {
	/* zeros-tail variant (cksum dd) */
	{ 0xcd,0xea,0x01,0x00,0x00,0x1a,0x00,0x00,0x00,0x03,0x00,0x00,0x00,0x01,0x00,0x00,
	  0x00,0x00,0x00,0x03,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xdd },
	/* our-MAC variant — M-200-exact template (c9:cc:03 at [9:15]); MAC_IDX=9
	 * substitutes OUR MAC + recomputes the cksum, so [9:15]/[33] are placeholders. */
	{ 0xcd,0xea,0x01,0x00,0x00,0x1a,0x00,0x00,0x00,0x00,0x40,0xab,0xc9,0xcc,0x03,0x00,
	  0x00,0x00,0x00,0xff,0xff,0xff,0xff,0xff,0xff,0x00,0x00,0x00,0x00,0xff,0xff,0xff,0xff,0x6c },
	/* "SYSP" variant — M-200-exact (SYSP at block idx 23; was shifted +1) */
	{ 0xcd,0xea,0x01,0x00,0x00,0x1a,0x00,0xff,0xff,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x53,0x59,0x53,0x50,0x01,0x00,0x00,0x00,0x00,0x00,0x97 },
	/* "SCEN" variant — M-200-exact (SCEN at block idx 17) */
	{ 0xcd,0xea,0x01,0x00,0x00,0x1a,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	  0x00,0x53,0x43,0x45,0x4e,0x01,0x00,0x00,0x00,0x03,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0xb7 },
};

/* The ENROLL / prepare-to-grant frame (cdea 01 03 000d), byte-exact from a real
 * M-200 (matrix-m200-s0808): emitted ONCE ~1.7 s before the grant burst, on the
 * COLD_CONNECT/CONFIG latch. It is the ONLY master control op reac-pw was missing
 * (verified by op-set diff). The box must RECEIVE this to arm itself to consume the
 * subsequent grant and advance to its own ESTABLISHED — without it the box stays in
 * a coldconnect-like "waiting" state, streams unicast but never heartbeats, and its
 * light BLINKS (rig 2026-07-12). Sums to 0 over [18:50] so apply_block re-stamp is a
 * no-op. */
static const uint8_t ENROLL_BLK[34] = {
	0xcd, 0xea, 0x01, 0x03, 0x00, 0x0d, 0x10, 0x04, 0x00, 0x41, 0x00, 0x00,
	0x00, 0x00, 0x00, 0xc3, 0xc3, 0xc3, 0xc3, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x8e
};
#define REAC_ENROLL_CONSOLE_IDX 8   /* ENROLL_BLK[8] = console-model byte (0/1) */

/* The mixer profiles reac-pw can impersonate. MAC + console_field are the only
 * per-mixer identity; the grants are box-defined. MACs are the captured desk
 * addresses (matrix-m{200,300,5000}-*). M-200/M-300 are V-Mixer (console 0);
 * M-5000 is OHRCA (console 1). */
static const struct reac_mixer_profile MIXER_PROFILES[] = {
	{ "m200",  "M-200",  { 0x00,0x40,0xab,0xc9,0xcc,0x03 }, 0 },
	{ "m300",  "M-300",  { 0x00,0x40,0xab,0xc9,0xd8,0x5b }, 0 },
	{ "m5000", "M-5000", { 0x00,0x40,0xab,0xca,0x15,0x4c }, 1 },
};

const struct reac_mixer_profile *reac_mixer_profile_by_name(const char *name)
{
	if (!name) return NULL;
	for (size_t i = 0; i < sizeof MIXER_PROFILES / sizeof MIXER_PROFILES[0]; i++)
		if (strcmp(name, MIXER_PROFILES[i].name) == 0)
			return &MIXER_PROFILES[i];
	return NULL;
}

const struct reac_mixer_profile *reac_mixer_profile_at(int i)
{
	if (i < 0 || (size_t)i >= sizeof MIXER_PROFILES / sizeof MIXER_PROFILES[0])
		return NULL;
	return &MIXER_PROFILES[i];
}

int reac_mixer_resolve_rate(const struct reac_mixer_profile *mixer, int requested, int *clamped)
{
	int native = (mixer && mixer->console_field != 0) ? 96000 : 48000;
	if (clamped)
		*clamped = 0;
	if (mixer && mixer->console_field != 0)
		return requested ? requested : native;   /* OHRCA: honor --rate, default 96k */
	if (requested && requested != native && clamped)
		*clamped = 1;                            /* V-Mixer: 48k always, report the override */
	return native;
}

/* Build the probe for the CURRENT burst position + link state, publish its
 * checksum as the FILLER descriptor (every FILLER until the next probe carries
 * it — byte-verified against the M-200: P:de -> F:de x16 -> P:dd -> F:dd x16 ...),
 * then advance the rotation. m->probe_idx (set by the cadence) selects the 4
 * inventory specials at in-burst indices 30..33; all other indices emit the
 * rotating hunt probe. Called when the cadence decides to emit a PROBE, BEFORE
 * reac_master_stamp reads m->probe_blk. */
static void probe_prepare(struct reac_master *m)
{
	int sp = m->probe_idx - REAC_PROBE_SPECIAL_FIRST;
	if (sp >= 0 && sp < REAC_PROBE_SPECIAL_COUNT) {
		memcpy(m->probe_blk, PROBE_SPECIALS[sp], 34);
		if (sp == 1) {   /* the MAC special advertises OUR identity */
			memcpy(m->probe_blk + PROBE_SPECIAL_MAC_IDX, m->src, 6);
			stamp_block_cksum(m->probe_blk);
		}
		m->filler_desc = m->probe_blk[33];
		return;          /* the rotation is not advanced by a special */
	}

	uint8_t sub = (m->state == REAC_M_ESTABLISHED) ? 0x03 : 0x02;
	gen_probe(m->probe_blk, m->probe_phase, sub);
	m->filler_desc = m->probe_blk[33];

	if (++m->probe_repeat >= REAC_PROBE_REPEAT) {
		m->probe_repeat = 0;
		m->probe_phase = (m->probe_phase + REAC_PROBE_PHASE_STEP) % REAC_PROBE_PERIOD;
	}
}

/* Generate the cfea master-announce from the console cfg + OUR src MAC.
 *
 * cfea width byte (out[18], the byte AFTER the fixed 0x28=40-slot total): CORRECTED
 * 2026-07-11 by a two-model M-200 compare (S-1608 vs S-0808 on desk c9:cc:03) — it
 * is the CONNECTED BOX's INPUT width, NOT the box output count: idle default 0x08,
 * 0x10 once a 16-in S-1608 links, 0x08 once an 8-in S-0808 links, with a box-count
 * field going 0x0000 -> 0x0001 (out[20:22]). Both boxes are 8-OUT yet the byte
 * differs, so it tracks INPUT; the chanmap (which follows OUTPUT width) is identical
 * for both. FIXED 2026-07-13: out[18]=cfg->out_channels was previously left STATIC
 * at the init-time default (0x08) regardless of the box that actually linked — the
 * box's own declared width, parsed off its cdea 01 03 0010 config-announce, was
 * discarded by the recognizer instead of feeding this field. reac_master_set_box
 * now writes the recognized box's in_ch into cfg->out_channels and re-stamps
 * announce_blk immediately (grant/recognition time), so a live S-1608 gets 0x10
 * and an S-0808 keeps 0x08. NOT modeled: reverting to the 0x08 idle default on
 * drop/peer-gone — no golden capture of a real M-200's disconnect transition
 * exists, so cfg->out_channels simply holds the last-recognized box's width
 * until a DIFFERENT box is recognized (reac_pacer only calls set_box on a model
 * change, matching the existing grant_burst carry-over). Flagged for the next
 * capture pass. */
static void gen_cfea(uint8_t out[34], const uint8_t src[6],
                     const struct reac_console_cfg *cfg, uint16_t box_count)
{
	static const uint8_t head[11] =
		{ 0xcf, 0xea, 0xff, 0xff, 0x01, 0x00, 0x01, 0x03, 0x0d, 0x01, 0x04 };
	memset(out, 0, 34);
	memcpy(out, head, 11);
	memcpy(out + ANNOUNCE_MAC_IDX, src, 6);   /* OUR MAC = the L2 source */
	out[17] = 0x28;                 /* 40: the FIXED REAC downstream slot total   */
	out[18] = cfg->out_channels;    /* box INPUT width (see note above); carried
	                                 * in by reac_master_set_box on recognition */
	out[19] = cfg->console_field;   /* console model (M-300 = 0, M-5000 = 1)      */
	/* [20:22] = the ENROLLED-BOX COUNT (big-endian). THE blink fix (2026-07-12):
	 * a real M-200 announces 0x0001 here once a box is enrolled; reac-pw hard-wired
	 * 0x0000 (the old out[21]=console_field was wrong — [19] and [21] are NOT the
	 * same field: [19]=console model, [21]=box-count low). Announcing 0 boxes made
	 * the box see itself UNACKNOWLEDGED, so it withheld its 01030001 heartbeat and
	 * kept its light BLINKING despite a clean grant + 1/s cadence + unicast link.
	 * Verified on the wire: box heartbeats to a count=1 master, silent to count=0. */
	out[20] = (uint8_t)(box_count >> 8);
	out[21] = (uint8_t)(box_count & 0xff);
	/* [22:33] stay zero */
	stamp_block_cksum(out);
}

/* The channel-map SWEEP a real master advertises. GROUND TRUTH: a LIVE M-200
 * (00:40:ab:c9:cc:03) driving a real S-1608 to sync, captured 2026-07-11 on the
 * rig. It emits FORTY-NINE distinct cdea 01 03 0019 windows — one per fabric ring
 * position — cycling continuously.
 *
 * THE FABRIC IS A RING of 49 positions: channels 0x00..0x2f (48) then the 0xfe
 * section marker at the wrap. A window advertises 8 CONSECUTIVE ring positions, so
 * windows near the wrap run through the marker and back to 0x00 (e.g. start 0x2f ->
 * 2f fe 00 01 02 03 04 05). One window per start position => exactly 49.
 *
 * WHY THE FULL SWEEP: §4 (S-1608 firmware FUN_0c003548) — a box recognizes a master
 * ONLY once it has seen the window that maps ITS OWN slots. The original code
 * derived the map from the local console's out_channels and emitted a SINGLE
 * 0x00..0x06 window, so no real box ever saw its channels and every one stayed
 * mute (#130). A first fix emitted 11 windows — but that figure came from an M-300
 * capture too SHORT to hold the whole rotation; the live M-200 shows the true 49.
 * The master advertises the FABRIC, never the console width: cfg is unused.
 *
 * Slot encoding: the 0xfe marker -> (fe 00 00); a channel ch -> (ch, val, 00) with
 * val 0x28 for ch <= 0x27 and 0x38 for the high bank 0x28..0x2f. apply_block
 * re-checksums at emit time, so only the slot bytes matter here; stamp_block_cksum
 * keeps the stored template self-consistent too. This generator reproduces the
 * captured windows byte-for-byte incl. checksums (tests/test_reac_s1608.c). */
#define REAC_CHANMAP_MARKER 0xfe
#define REAC_CHANMAP_SLOTS   8   /* ring positions advertised per frame */

/* The fabric RING: 49 positions — channels 0x00..0x2f (ring idx 0..47) then the
 * 0xfe section marker at the wrap (idx 48). */
static uint8_t ring_at(int i)
{
	i %= REAC_M_FABRIC_RING;
	return (i == REAC_M_FABRIC_RING - 1) ? REAC_CHANMAP_MARKER : (uint8_t)i;
}

/* The master's window emit ORDER (measured off the M-200): the marker window
 * first, then base 7 down to 0, each base stepping by 8 —
 *   fe · 07 0f 17 1f 27 2f · 06 0e 16 1e 26 2e · … · 00 08 10 18 20 28
 * i.e. 1 + 8*6 = 49 windows. Returns the ring START index of frame f. */
static int chanmap_start(int f)
{
	if (f == 0)
		return REAC_M_FABRIC_RING - 1;      /* the 0xfe marker window */
	int i    = f - 1;                       /* 0..47 */
	int base = 7 - (i / 6);                 /* 7,6,5,4,3,2,1,0 */
	int k    = i % 6;                       /* 0..5 */
	return base + 8 * k;
}

/* Populate `frames` with the full 49-window fabric sweep (returns the count).
 * cfg is unused: the master advertises the whole FABRIC, never the console's own
 * width (see the block comment above). */
static int gen_chanmap(uint8_t frames[][34], const struct reac_console_cfg *cfg)
{
	(void)cfg;
	for (int f = 0; f < REAC_M_FABRIC_RING; f++) {
		uint8_t *blk = frames[f];
		memset(blk, 0, 34);
		blk[0] = 0xcd; blk[1] = 0xea;
		blk[2] = 0x01; blk[3] = 0x03;         /* established sub-state 0x03 */
		blk[4] = 0x00; blk[5] = 0x19;         /* BE len 0x0019 (fixed)      */
		blk[6] = 0x01;                        /* payload-type = 1           */
		int start = chanmap_start(f);
		for (int s = 0; s < REAC_CHANMAP_SLOTS; s++) {
			uint8_t ch = ring_at(start + s);
			uint8_t *t = blk + 7 + s * 3;     /* 3-byte slot */
			if (ch == REAC_CHANMAP_MARKER) {
				t[0] = 0xfe; t[1] = 0x00; t[2] = 0x00;  /* section marker */
			} else {
				t[0] = ch;
				/* 0x38 for the high bank (0x28..0x2f), else 0x28. */
				t[1] = (ch >= 0x28 && ch <= 0x2f) ? 0x38 : 0x28;
				t[2] = 0x00;
			}
		}
		blk[31] = 0x00; blk[32] = 0x00;       /* terminator */
		stamp_block_cksum(blk);
	}
	return REAC_M_FABRIC_RING;
}

/* Allocate `in_ch` fabric slots and regenerate the grant sweep for them. Keeps the
 * current allocation + sweep on a width we cannot place (the caller logs it), so a
 * bogus recognition can never leave the master with an EMPTY grant. Shared by init,
 * reac_master_set_box and reac_master_set_headamp_src — the sweep is a pure
 * function of (alloc, headamp_src), so every input change funnels through here. */
static int rebuild_grant_sweep(struct reac_master *m, int in_ch)
{
	struct reac_grant_alloc a;
	if (reac_grant_allocate(&a, in_ch) != 0)
		return -1;
	int n = reac_grant_build_sweep(m->grant_burst, REAC_GRANT_SWEEP_MAX, &a,
	                               m->headamp_src);
	if (n <= 0)
		return -1;
	m->alloc = a;
	m->grant_burst_len = n;
	return 0;
}

const char *reac_master_state_name(enum reac_master_state s)
{
	switch (s) {
	case REAC_M_IDLE:        return "IDLE";
	case REAC_M_PROBING:     return "PROBING";
	case REAC_M_GRANTING:    return "GRANTING";
	case REAC_M_ESTABLISHED: return "ESTABLISHED";
	}
	return "?";
}

const char *reac_master_rx_event_name(enum reac_master_rx_event e)
{
	switch (e) {
	case REAC_M_RX_BOX_BCAST_FILLER: return "BCAST-FILLER";
	case REAC_M_RX_BOX_JOIN:         return "JOIN";
	case REAC_M_RX_BOX_UNICAST:      return "UNICAST";
	case REAC_M_RX_BOX_HEARTBEAT:    return "HEARTBEAT";
	case REAC_M_RX_BOX_BYE:          return "BYE";
	case REAC_M_RX_BOX_CONFIG:       return "CONFIG";
	}
	return "?";
}

const char *reac_master_drop_name(enum reac_master_drop_reason r)
{
	switch (r) {
	case REAC_M_DROP_NONE:          return "none";
	case REAC_M_DROP_PEER_GONE:     return "peer-gone";
	case REAC_M_DROP_BYE:           return "explicit-BYE";
	case REAC_M_DROP_MAC_CHANGE:    return "box-mac-change";
	case REAC_M_DROP_GRANT_TIMEOUT: return "grant-timeout";
	}
	return "?";
}

/* OPTIONAL OVERRIDE (default UNSET = today's timing, byte-identical):
 * REACPW_GRANT_DWELL_S=N holds the recognized-but-ungranted dwell for N WHOLE
 * SECONDS before the grant burst, replacing the built-in ~1.6 s dwell
 * (REAC_M_GRANT_DWELL_SECONDS_X10/10). A real M-200 holds a cold box ungranted
 * ~27 s — the box climbs its op0403/TAG0100 JOIN field 01->05->0d meanwhile —
 * before granting; reac-pw's ~1.6 s dwell grants too fast for the box to react,
 * so REACPW_GRANT_DWELL_S=30 gives a ~30 s recognized-ungranted hold. ONLY the
 * dwell LENGTH changes: the FSM still runs ENROLL->dwell->burst->ESTABLISHED,
 * the dwell keeps emitting the w0x10/cnt0 announce (REACPW_ANNOUNCE_UNGRANTED,
 * default ON), and the same-box GRANTING guard in reac_master_rx keeps the box's
 * repeated cold-connect JOIN retries from restarting the dwell. Returns the
 * override in SECONDS, or -1 when UNSET / non-numeric / non-positive (leave the
 * built-in dwell untouched). Read once + cached, matching the file's other
 * getenv knobs. */
static int grant_dwell_override_s(void)
{
	static int cached = -2;   /* -2 = unread, -1 = unset/invalid, >0 = seconds */
	if (cached == -2) {
		const char *v = getenv("REACPW_GRANT_DWELL_S");
		cached = -1;
		if (v && v[0]) {
			char *end = NULL;
			long n = strtol(v, &end, 10);
			if (end && *end == '\0' && n > 0 && n <= 3600)
				cached = (int)n;
		}
	}
	return cached;
}

void reac_master_init(struct reac_master *m, const uint8_t src[6],
                      const struct reac_console_cfg *cfg, int fps)
{
	memset(m, 0, sizeof *m);
	m->state = REAC_M_IDLE;
	memcpy(m->src, src, 6);
	m->fps = fps > 0 ? fps : 8000;
	m->cfg = cfg ? *cfg : REAC_CONSOLE_CFG_S1608;

	/* The cycle-locked control choreography, all slot offsets measured on the
	 * M-300/S-1608 establish capture at 4000 fps and scaled by fps (see the
	 * struct doc): cycle 10778 slots; probes every 8 slots through slot 2720
	 * (341/burst incl. the 4 specials at indices 30..33); sub02 at 2728;
	 * chanmap at 5953; sub01 at 10773 (cycle_len - 5). */
	m->cycle_len    = (int)(((int64_t)m->fps * 10778) / 4000);
	m->probe_stride = m->fps / 500;
	if (m->probe_stride < 1)
		m->probe_stride = 1;
	m->burst_end    = (341 - 1) * m->probe_stride;
	m->sub02_off    = m->burst_end + m->probe_stride;
	m->chanmap_off  = (int)(((int64_t)m->fps * 5953) / 4000);
	m->sub01_off    = m->cycle_len - 5;
	/* ~150 ms grant window, one echoed grant per stride (~100 frames total). */
	m->grant_frames = (m->fps * 15) / 100;
	if (m->grant_frames < 1)
		m->grant_frames = 1;
	m->grant_stride = REAC_M_GRANT_STRIDE;
	/* ENROLL->grant dwell: a real M-200 waits ~1.6 s between emitting ENROLL and
	 * starting the grant burst (measured Δ1.503 s on matrix-m200-s0808-2026-07-11.pcap,
	 * Δ1.717 s on matrix-m200-s1608-2026-07-11.pcap — both real M-200 goldens,
	 * reac-captures/captures/). The RX-driven rewrite invoked enter_granting()
	 * synchronously off the box's JOIN/CONFIG frame and the very next pacer tick
	 * started the burst, dropping this dwell — the same failure class the repo's
	 * own history calls out ("GRANTING->ESTABLISHED in 0.25 ms... box LED blinking
	 * faster, never stabilising"). fps-scaled like link_check_reload, frame-counted
	 * (not wall-clock — the pacer is tick-driven). */
	m->grant_dwell = (m->fps * REAC_M_GRANT_DWELL_SECONDS_X10) / 10;
	if (m->grant_dwell < 1)
		m->grant_dwell = 1;
	/* REACPW_GRANT_DWELL_S=N (default UNSET) overrides the ~1.6 s dwell to hold the
	 * recognized-but-ungranted window for N seconds — fps-scaled + frame-counted,
	 * same as the default above — so the box gets the ~27 s hold a real M-200 gives
	 * it. UNSET leaves the default exactly as computed (byte-identical). */
	{
		int dwell_s = grant_dwell_override_s();
		if (dwell_s > 0)
			m->grant_dwell = m->fps * dwell_s;
	}
	/* Allocate the fabric slots for the console's declared box and GENERATE the
	 * enrollment sweep for that allocation. The recognizer re-allocates + re-builds
	 * per autodetected model via reac_master_set_box.
	 *
	 * The default now follows cfg.in_channels (the box width this console config
	 * declares — 16 for the S-1608 default), where the old code defaulted to a
	 * replayed S-0808 table regardless of cfg: the default sweep and the default
	 * cfg used to disagree with each other, which is precisely the desync class
	 * this task removes. */
	m->headamp_src = NULL;                     /* safe defaults until set */
	/* cfg.in_channels is now LOAD-BEARING (it sizes the grant), where before this
	 * task the grant ignored cfg entirely and defaulted to a replayed S-0808 table.
	 * A caller that leaves it 0 would allocate nothing and we would emit an EMPTY
	 * grant — a silent, box-mute failure. Fall back to the documented S-1608
	 * default width instead, which is what cfg == NULL already means. */
	int in_ch = m->cfg.in_channels;
	if (rebuild_grant_sweep(m, in_ch) != 0) {
		rebuild_grant_sweep(m, REAC_CONSOLE_CFG_S1608.in_channels);
		m->cfg.in_channels = REAC_CONSOLE_CFG_S1608.in_channels;
	}
	/* Peer-gone budget = ~6.5 s of frames (the measured M-200i hold), rate-scaled
	 * so it is the same wall-clock at 44.1/48/96k (#130). */
	m->link_check_reload = (m->fps * REAC_M_LINKCHECK_SECONDS_X10) / 10;
	if (m->link_check_reload < 1)
		m->link_check_reload = 1;

	/* Generate the downstream the master advertises for this console: the 49-window
	 * fabric sweep + the cfea announce (OUR src MAC embedded). */
	m->chanmap_nframes = gen_chanmap(m->chanmap, &m->cfg);
	gen_cfea(m->announce_blk, m->src, &m->cfg, 0);   /* idle: 0 boxes enrolled */
	/* ENROLL for this mixer: the console-model byte follows the profile
	 * (V-Mixer 0 / OHRCA 1). apply_block re-checksums at stamp time. */
	memcpy(m->enroll_blk, ENROLL_BLK, 34);
	m->enroll_blk[REAC_ENROLL_CONSOLE_IDX] = m->cfg.console_field;
	stamp_block_cksum(m->enroll_blk);

	/* Seed the probe rotation at phase 0 / sub 0x02 (hunting) so FILLER frames
	 * carry a valid descriptor from the very first slot, before any probe fires. */
	m->probe_phase  = 0;
	m->probe_repeat = 0;
	gen_probe(m->probe_blk, m->probe_phase, 0x02);
	m->filler_desc = m->probe_blk[33];
}

/* Allocate the fabric slots for the autodetected box (recognizer #137) and
 * regenerate the enrollment sweep for them. Keyed on the box's INPUT width: the
 * sweep enrolls the box's INPUTS, and S-0808/S-1608 are both 8-OUT, so the output
 * count cannot distinguish them.
 *
 * REPLACES (2026-07-17) the old "pick one of three transcribed tables" selector.
 * Those tables were replays of a real M-200 granting a SPECIFIC box, and the
 * default was the S-0808's — so any box whose width we failed to recognize was
 * handed an 8-input, base-0x00 enrollment. An S-1608 given that sweep LINKS, and
 * then ignores every head-amp record we address to CH 0x20 because our own grant
 * never claimed those slots (live 2026-07-17: 28 byte-perfect records, 48V never
 * lit). Generating from our allocation makes the grant and the later head-amp
 * traffic agree by construction — they now read the same `alloc`.
 *
 * ALSO carries the box's declared INPUT width into the cfea announce (FIXED
 * 2026-07-13): a real M-200 announces cfea out[18] as the CONNECTED box's input
 * width (0x10 for an S-1608, 0x08 for an S-0808 — see the gen_cfea block comment),
 * but reac_ctrl.c's config-announce parser (~line 160) only classifies the RX
 * event and never threaded the box's width through, so out[18] stayed frozen at
 * whatever reac_master_init's cfg started with. We now stamp cfg.out_channels
 * (the field gen_cfea reads) and re-generate+re-checksum announce_blk right here,
 * at recognition time — enter_granting's own gen_cfea call (fired moments later
 * by the same RX event, see reac_pacer.c) then just re-confirms it with the
 * latched box_count. */
void reac_master_set_box(struct reac_master *m, int in_ch, int out_ch)
{
	(void)out_ch;   /* S-0808 and S-1608 are both 8-OUT — the INPUT width distinguishes */
	/* Allocate width-many contiguous fabric slots for this box and rebuild group A
	 * over them (group B is width-invariant). A width we cannot place keeps the
	 * current sweep — never an empty grant. */
	rebuild_grant_sweep(m, in_ch);

	m->cfg.out_channels = (uint8_t)in_ch;    /* cfea width byte := box input width */
	uint16_t box_count = (m->state == REAC_M_GRANTING ||
	                      m->state == REAC_M_ESTABLISHED) ? 1 : 0;
	gen_cfea(m->announce_blk, m->src, &m->cfg, box_count);
}

void reac_master_set_headamp_src(struct reac_master *m,
                                 const struct reac_headamp_tx *tx)
{
	m->headamp_src = tx;
	/* Rebuild so the next grant enrolls the CURRENT head-amp state. Same
	 * allocation — only group A's values change. */
	rebuild_grant_sweep(m, m->alloc.width);
}

/* A/B TOGGLE (default ON): REACPW_ANNOUNCE_UNGRANTED.
 *
 * Model the real M-200's RECOGNIZED-BUT-UNGRANTED window (reac-firmware-re/
 * HEADAMP-MASTER-STATE-2026-07-17.md, Update 9 "Lead A"): once a box is
 * recognized the desk announces the cfea with the BOX WIDTH already set but the
 * box-count field STILL 0, and HOLDS that announced through the ENTIRE
 * ENROLL->grant dwell, flipping to count=1 only at grant. That held window is
 * believed to be what commits 48V on the ANCHOR / last box input; without it
 * reac-pw jumps idle(count0)->granted(count1) and the anchor input never sees the
 * ungranted state on the wire.
 *
 *   ON  (default): enter_granting announces count=0 (width already stamped by
 *                  reac_master_set_box at recognition); the GRANTING dwell emits
 *                  the cfea announce cadence (count=0) instead of hard FILLER, so
 *                  the recognized-but-ungranted window actually reaches the wire
 *                  for the full dwell; count flips to 1 at enter_established.
 *   OFF (REACPW_ANNOUNCE_UNGRANTED=0): the prior behaviour — count=1 latched at
 *                  enter_granting (the 2026-07-12 blink fix) and hard FILLER
 *                  through the dwell. Establishment is byte-unchanged when off.
 *
 * The anchor-commit theory is unconfirmed and this touches the establishment
 * cadence, so it stays A/B-able on the rig WITHOUT a rebuild. Read once + cached:
 * the pacer calls the FSM at wire rate. */
static int announce_ungranted_enabled(void)
{
	static int cached = -1;
	if (cached < 0) {
		const char *v = getenv("REACPW_ANNOUNCE_UNGRANTED");
		cached = (v && (v[0] == '0' || v[0] == 'n' || v[0] == 'N')) ? 0 : 1;
	}
	return cached;
}

/* A/B TOGGLE (default OFF): REACPW_ANNOUNCE_BURST — hypothesis #1 extension.
 *
 * Builds ON REACPW_ANNOUNCE_UNGRANTED. That flag holds the count=0 recognized-but-
 * ungranted cfea (box width set, box-count 0 in announce_blk) and re-emits it on the
 * ~1/s announce cadence through the ENROLL->grant DWELL only. Dwell-only announce did
 * NOT elicit the real M-200's box escalation on the rig: the box's op0403 TAG0100 JOIN
 * field stays 01 (never climbs 01->05->0d), so per-input phantom never commits.
 *
 * With THIS flag ON, the same count=0 ungranted window ALSO reaches the wire on the
 * free-running announce_tick THROUGHOUT the grant BURST — the FILLER slots between the
 * actual GRANT slots become cfea announces — so the box sees a PROLONGED recognized-
 * ungranted signal spanning the whole sweep, not just the dwell (hypothesis: that is
 * what climbs the JOIN field and finally commits phantom).
 *
 * ONLY meaningful with REACPW_ANNOUNCE_UNGRANTED also on: announce_blk must still hold
 * count=0 during GRANTING (enter_granting stamps it; enter_established flips it to 1).
 * Actual GRANT/ENROLL slots are NEVER displaced — only FILLER converts — so with this
 * flag OFF the burst path is byte-identical to today. Read once + cached like
 * announce_ungranted_enabled(): the pacer calls the FSM at wire rate. */
static int announce_burst_enabled(void)
{
	static int cached = -1;
	if (cached < 0) {
		const char *v = getenv("REACPW_ANNOUNCE_BURST");
		cached = (v && (v[0] == '1' || v[0] == 'y' || v[0] == 'Y' ||
		                v[0] == 't' || v[0] == 'T')) ? 1 : 0;
	}
	return cached;
}

/* NEW FLAG (default OFF): REACPW_EST_COMMIT — the post-establish scene COMMIT.
 *
 * With the flag OFF (unset) the established cadence AND the head-amp seed are
 * byte-identical to today. With it ON, two coupled behaviours arm: (1) the pacer
 * seeds every GRANTED head-amp channel (base..base+w-1) into the DMX send table at
 * open — operator value if set, else the safe default (reac_grant_headamp_value) —
 * so the whole 16x3 op-0403 scene is re-pushed post-establish and the box's staging
 * holds every channel; (2) enter_established arms est_commit so control_cadence emits
 * the ordered SUB01 -> SUB02 pair once, driving the box's scene-FSM state-4 bulk
 * commit (FUN_0c003c8a) that latches the whole preamp scene into hardware. Read once
 * + cached like the file's other getenv knobs (the static local IS the cache); the
 * pacer's open-time seed calls this FIRST (single-threaded, before the pacer thread
 * starts), so the cache is warm by the time enter_established reads it on the pacer
 * thread — no data race. */
int reac_master_est_commit_enabled(void)
{
	static int cached = -1;
	if (cached < 0) {
		const char *v = getenv("REACPW_EST_COMMIT");
		cached = (v && (v[0] == '1' || v[0] == 'y' || v[0] == 'Y' ||
		                v[0] == 't' || v[0] == 'T')) ? 1 : 0;
	}
	return cached;
}

/* Restart the control cycle at slot 0 (the burst head — the first slot emits a
 * probe, exactly like a real master opening a hunt burst). cfea free-runs on its
 * own ~1/s tick, phase-offset so it lands in the pause region, never on a burst
 * probe slot. */
static void reset_control_cadence(struct reac_master *m)
{
	m->cycle_pos       = 0;
	m->announce_tick   = (3 * m->fps) / 4;
	m->chanmap_cursor  = 0;
	m->est_chanmap_tick = m->fps / 4;   /* offset ~0.5 s from cfea so the two
	                                     * 1/s locked keep-alives never collide */
}

/* Enter PROBING with a fresh control cadence (from IDLE, a grant timeout, or an
 * established drop). The counter is NOT touched — it free-runs. */
static void enter_probing(struct reac_master *m)
{
	m->state = REAC_M_PROBING;
	reset_control_cadence(m);
	gen_cfea(m->announce_blk, m->src, &m->cfg, 0);   /* no box enrolled */
}

/* Open a grant window (ENROLL, then the grant_dwell hold, then the burst)
 * echoing this JOIN block. Re-opens on a JOIN from a DIFFERENT box — including
 * one that arrives mid-window or while established — since that is a new box
 * to court; a JOIN from the SAME box mid-window is a retry and must NOT reset
 * it (reac_master_rx's same-box guards, GRANTING and ESTABLISHED). */
static void enter_granting(struct reac_master *m, const uint8_t box_src[6],
                           const uint8_t blk32[32])
{
	m->state = REAC_M_GRANTING;
	m->grant_ticks = 0;
	m->grant_attempts++;
	memcpy(m->box_mac, box_src, 6);
	if (blk32)
		memcpy(m->join_blk, blk32, 32);
	/* cfea box-count on latch. With REACPW_ANNOUNCE_UNGRANTED (default ON) we hold
	 * count=0 so the announce carries the RECOGNIZED-BUT-UNGRANTED window a real M-200
	 * holds through the whole dwell; the count flips to 1 at enter_established.
	 *
	 * That window must carry the RECOGNIZED BOX WIDTH, not the idle cfea default.
	 * gen_cfea's width byte is cfg.out_channels, which reac_master_set_box only widens
	 * to the box width on the box's CONFIG-announce recognition — but a cold-connect
	 * JOIN (cdea 04 03) reaches GRANTING BEFORE that recognition (the JOIN does not
	 * identify the model), so here cfg.out_channels can still be the idle 0x08 and the
	 * dwell announce went out as w0x08/cnt0, never the w0x10/cnt0 a real M-200 emits.
	 * m->alloc.width already holds the granted box width in BOTH paths (init-seeded
	 * from cfg.in_channels, re-set by reac_master_set_box) and is exactly the width
	 * the w0x10/cnt1 granted announce carries, so build the ungranted announce from it
	 * with count=0.
	 *
	 * With the flag OFF we keep the prior count=1-on-latch behaviour straight off
	 * m->cfg (the box sees itself acknowledged pre-lock — the 2026-07-12 blink fix),
	 * so establishment is byte-unchanged when A/B'd off. */
	/* Stamp the recognized width PERSISTENTLY into m->cfg (not a throwaway copy) so the
	 * count=1 GRANTED announce enter_established re-emits from m->cfg carries it too. The
	 * throwaway-copy version widened only the dwell, so on cold-connect the granted announce
	 * COLLAPSED to w0x08/cnt1 the instant the box latched (verified: w0x10/cnt1=0 on the wire) —
	 * the box never held a stable 16-wide recognition through the commit. m->alloc.width holds
	 * the recognized width here (init-seeded from cfg.in_channels, re-set by reac_master_set_box). */
	m->cfg.out_channels = m->alloc.width;
	gen_cfea(m->announce_blk, m->src, &m->cfg,
	         announce_ungranted_enabled() ? 0 : 1);
}

static void enter_established(struct reac_master *m)
{
	m->state = REAC_M_ESTABLISHED;
	/* Same continuous control cadence as PROBING (PROBE + the four 1/s
	 * streams), phase-offset so they never contend for a slot. */
	reset_control_cadence(m);
	m->link_check = m->link_check_reload;
	/* Arm the one-shot post-establish scene COMMIT (REACPW_EST_COMMIT, default OFF):
	 * count down (fps/SCENE_SETTLE_DEN + SUB_GAP) FILLER-eligible slots so
	 * control_cadence fires SUB01 once the post-establish head-amp scene re-push has
	 * settled, then SUB02 SUB_GAP slots later — the ordered pair that drives the box's
	 * scene-FSM state-4 bulk phantom commit. OFF leaves est_commit 0 (never armed), so
	 * the commit block in control_cadence is inert and the locked cadence is
	 * byte-identical to today. Re-armed on every establishment -> fires ONCE each. */
	m->est_commit = reac_master_est_commit_enabled()
		? m->fps / REAC_M_EST_COMMIT_SCENE_SETTLE_DEN + REAC_M_EST_COMMIT_SUB_GAP
		: 0;
	/* GRANT confirmed -> announce the box as GRANTED (count=1). This is the flip a
	 * real M-200 makes at grant: with REACPW_ANNOUNCE_UNGRANTED the announce held
	 * count=0 (recognized-but-ungranted) through the dwell+burst and rises to 1
	 * exactly here. Idempotent when the flag is off (enter_granting already latched
	 * count=1). enter_established is only ever reached from GRANTING, where enter_granting
	 * STAMPED the recognized width into m->cfg, so this granted announce carries it too —
	 * no width collapse at latch. */
	gen_cfea(m->announce_blk, m->src, &m->cfg, 1);
}

int reac_master_rx(struct reac_master *m, enum reac_master_rx_event ev,
                   const uint8_t box_src[6], const uint8_t blk32[32])
{
	/* Any box frame is presence (diagnostic only — never gates the grant). */
	m->box_seen = 1;
	m->presence_tick = REAC_M_PRESENCE_TIMEOUT;

	/* The pacer is ticking us if RX arrives; IDLE only means "first slot not
	 * emitted yet" — treat it as PROBING so an early JOIN is not lost. */
	if (m->state == REAC_M_IDLE)
		enter_probing(m);

	switch (m->state) {
	case REAC_M_IDLE:   /* unreachable (promoted above) */
	case REAC_M_PROBING:
		if (ev == REAC_M_RX_BOX_JOIN && blk32) {
			enter_granting(m, box_src, blk32);
			return 1;
		}
		if (ev == REAC_M_RX_BOX_CONFIG) {
			/* WARM RELINK: a previously-synced box skips flood + cold-connect
			 * and re-appears streaming unicast, re-declaring itself with its
			 * config-announce (no 04 03 JOIN). This is a SPECIFIC checksum-valid
			 * frame, not mere presence, so it does not break the anti-#130 rule.
			 * Route it through GRANTING to fire the 32-frame grant burst — the
			 * frame the box needs to cross GRANTING->LOCKED and go SOLID. The
			 * earlier cut jumped straight to ESTABLISHED and skipped the burst,
			 * which is exactly why the box reached our-side established but its
			 * own light kept BLINKING (measured 2026-07-12, matrix-m200-s0808:
			 * the real M-200 emits the burst here). */
			enter_granting(m, box_src, NULL);
			return 1;
		}
		/* Presence-flood / stray unicast: diagnostic only. Presence alone
		 * must NOT trigger the grant (the anti-#130 golden rule). */
		return 0;

	case REAC_M_GRANTING:
		if (ev == REAC_M_RX_BOX_JOIN && blk32) {
			/* The SAME box keeps cold-connecting on its own ~100 ms retry grid
			 * for as long as it hasn't seen the grant — which now spans the
			 * ~1.6 s ENROLL->grant dwell (grant_dwell) too. Resetting on every
			 * such retry would perpetually restart the dwell and the box would
			 * never be granted, so HOLD for the same box (symmetric to the
			 * same-box hold already used in ESTABLISHED, below). A JOIN from a
			 * DIFFERENT box is a genuinely new box: re-latch and restart the
			 * window for it. */
			if (memcmp(box_src, m->box_mac, 6) != 0) {
				enter_granting(m, box_src, blk32);
				return 1;
			}
			return 0;
		}
		if (ev == REAC_M_RX_BOX_HEARTBEAT) {
			/* The box's heartbeat = it has LOCKED (reached its own ESTABLISHED).
			 * That is the definitive, timer-free confirmation — establish at once,
			 * no burst-gate needed (the box already accepted the grant). Symmetric
			 * to the heartbeat our slave emits once locked. */
			enter_established(m);
			return 1;
		}
		if (ev == REAC_M_RX_BOX_UNICAST || ev == REAC_M_RX_BOX_CONFIG) {
			/* The box's unicast is the accept — BUT only once the FULL 32-frame
			 * grant burst has been delivered. A cold-JOIN box switches to unicast
			 * AFTER it sees the grant, so this gate is already satisfied; a WARM-
			 * RELINK box is unicasting from the first slot, so without this gate the
			 * very next unicast cut the burst to ~1 frame and the box never locked
			 * solid (measured on the rig 2026-07-12: GRANTING->ESTABLISHED in 0.25 ms).
			 * Before the burst completes, the unicast only confirms presence (keeps
			 * granting); anti-#130 holds — establish still needs a box frame, never a
			 * blind timer, and the grant window still expires BACK to PROBING. */
			if (m->grant_ticks >= m->grant_dwell + m->grant_burst_len * m->grant_stride + 1) {
				enter_established(m);   /* +1: the leading ENROLL slot; +grant_dwell: the dwell */
				return 1;
			}
			return 0;
		}
		if (ev == REAC_M_RX_BOX_BYE) {
			m->drop_reason = REAC_M_DROP_BYE;
			enter_probing(m);
			return 1;
		}
		return 0;

	case REAC_M_ESTABLISHED:
		/* Every box RX event reloads the 600-frame link-check budget. */
		m->link_check = m->link_check_reload;
		if (ev == REAC_M_RX_BOX_BYE) {
			m->drop_reason = REAC_M_DROP_BYE;
			enter_probing(m);
			return 1;
		}
		if (ev == REAC_M_RX_BOX_JOIN && blk32) {
			/* A JOIN from a DIFFERENT box -> re-grant the new one. But the SAME
			 * box keeps JOINing on its cold-connect retry grid WHILE it completes
			 * its own TX_MUTE dwell to lock — re-granting on each such JOIN tore
			 * down the stable locked stream the box needs, so it never finished
			 * locking (rig 2026-07-12: box cold-connects forever, LED blinks faster,
			 * no heartbeat). HOLD ESTABLISHED for the same box (its JOINs just keep
			 * the link alive); only a MAC change re-courts. */
			if (memcmp(box_src, m->box_mac, 6) != 0) {
				m->drop_reason = REAC_M_DROP_MAC_CHANGE;
				enter_granting(m, box_src, blk32);
				return 1;
			}
			return 0;   /* same box still settling — stay locked, hold the stream */
		}
		return 0;
	}
	return 0;
}

/* The CYCLE-LOCKED control cadence a real master advertises in BOTH the unlinked
 * and the linked state, measured slot-exact on the M-300/S-1608 establish
 * capture (#130): one deterministic cycle of cycle_len slots holding a probe
 * BURST (one probe every probe_stride slots through burst_end — 341 probes with
 * the 4 inventory specials at in-burst indices 30..33), then a probe-free pause
 * carrying sub02 (right after the burst), ONE chanmap window (mid-pause; the
 * 49-window sweep spans 49 cycles) and sub01 (cycle tail). cfea free-runs at
 * ~1/s and defers by a slot when it collides with a cycle event — the real
 * desk's cfea lands between burst probes too.
 *
 * The old model (PROBE ~115/s uniform + all four streams at 1/s) was the DUTY-
 * CYCLE AVERAGE of this rhythm — an analysis artifact a real box never sees on
 * the wire, and plausibly the last tell that kept real boxes mute (#130).
 *
 * §4 (S-1608 firmware, FUN_0c003548): the box's parser recognizes a master ONLY
 * on the sub-state-0x03 channel-map (cdea 01 03 0019 ...), so the chanmap must
 * be advertised while unlinked too — a master that only probes deadlocks against
 * a box that only joins once it has seen a valid map. */
static enum reac_master_emit control_cadence(struct reac_master *m, int *idx)
{
	*idx = 0;
	int pos = m->cycle_pos;
	m->cycle_pos = (pos + 1) % m->cycle_len;
	m->announce_tick++;

	/* LOCKED cadence (measured slot-exact on matrix-m200-s0808, box SOLID): once
	 * established a real M-200 emits ONLY two control frames, each metronomic at
	 * 1.00/s — cfea + the chanmap (sub-state-0x03 map) — and NOTHING else (0
	 * probes, 0 sub01/sub02). The chanmap is the box's sync keep-alive; the old
	 * hunt-rate 1/cycle (~0.37/s) under-sent it and the box's light kept BLINKING
	 * (rig 2026-07-12). cfea and chanmap are phase-offset ~0.5 s so they never
	 * share a slot. */
	if (m->state == REAC_M_ESTABLISHED) {
		m->est_chanmap_tick++;
		if (m->announce_tick >= m->fps) {
			m->announce_tick = 0;
			return REAC_M_EMIT_ANNOUNCE;
		}
		if (m->est_chanmap_tick >= m->fps) {
			m->est_chanmap_tick = 0;
			*idx = m->chanmap_cursor;
			m->chanmap_cursor = (m->chanmap_cursor + 1) % m->chanmap_nframes;
			return REAC_M_EMIT_CHANMAP;
		}
		/* One-shot post-establish scene COMMIT (REACPW_EST_COMMIT, default OFF).
		 * enter_established arms est_commit ONLY when the flag is on; when off it is 0
		 * and this whole block is inert, so the LOCKED cadence stays byte-identical to
		 * today (cfea + chanmap only — the "0 sub01/sub02 established" invariant holds).
		 * When armed it counts down the FILLER-eligible slots reaching here (announce +
		 * chanmap already returned above, so this NEVER displaces a 1/s keep-alive and
		 * never collides with their offsets), and once the post-establish scene re-push
		 * has settled it drives the box's scene-FSM state-4 bulk phantom commit by
		 * emitting the ordered pair a real M-200 sends at scene recall: SUB01 first,
		 * then SUB02 SUB_GAP slots later. Reaching 0 disarms it -> fires exactly ONCE
		 * per establishment. SUB01/SUB02 are byte-identical to the M-200's, so the box
		 * accepts them and stays ESTABLISHED. */
		if (m->est_commit > 0) {
			m->est_commit--;
			if (m->est_commit == REAC_M_EST_COMMIT_SUB_GAP)
				return REAC_M_EMIT_SUB01;   /* strictly before SUB02 */
			if (m->est_commit == 0)
				return REAC_M_EMIT_SUB02;   /* disarmed: once per establishment */
		}
		return REAC_M_EMIT_FILLER;
	}

	/* HUNT cadence (PROBING; byte-measured on the M-300/S-1608 establish capture):
	 * the probe burst + sub02/chanmap/sub01 cycle events + cfea free-running. */
	if (pos <= m->burst_end && pos % m->probe_stride == 0) {
		m->probe_idx = pos / m->probe_stride;  /* specials key off this */
		return REAC_M_EMIT_PROBE;
	}
	if (pos == m->sub02_off)
		return REAC_M_EMIT_SUB02;
	if (pos == m->chanmap_off) {
		*idx = m->chanmap_cursor;
		m->chanmap_cursor = (m->chanmap_cursor + 1) % m->chanmap_nframes;
		return REAC_M_EMIT_CHANMAP;
	}
	if (pos == m->sub01_off)
		return REAC_M_EMIT_SUB01;
	if (m->announce_tick >= m->fps) {
		m->announce_tick = 0;
		return REAC_M_EMIT_ANNOUNCE;
	}
	return REAC_M_EMIT_FILLER;
}

enum reac_master_emit reac_master_next(struct reac_master *m, uint16_t *counter,
                                       int *tmpl_idx)
{
	*counter = m->counter;
	m->counter++;                 /* free-running, wraps at 16 bits like the desk's */

	/* First emitted slot: the pacer is running, so we probe — always. */
	if (m->state == REAC_M_IDLE)
		enter_probing(m);

	/* Presence diagnostic decay (logging only — never a state input). */
	if (m->box_seen && --m->presence_tick <= 0)
		m->box_seen = 0;

	enum reac_master_emit emit = REAC_M_EMIT_FILLER;
	int idx = 0;

	switch (m->state) {
	case REAC_M_IDLE:   /* unreachable (promoted above) */
	case REAC_M_PROBING:
		/* Unlinked: the full continuous control cadence. NO timer leaves this
		 * state — only a validated JOIN does (reac_master_rx). */
		emit = control_cadence(m, &idx);
		break;

	case REAC_M_GRANTING:
		/* Emit the master's own 32-frame grant burst (the byte-exact M-200 cdea
		 * 04 03 sweep), one distinct block every grant_stride slots — the SEND
		 * side of the exact transition reac-pw waited to RECEIVE as a slave (#130,
		 * same state diagram, roles inverted), but only AFTER the grant_dwell
		 * ENROLL->grant hold (~1.6 s, see its comment in reac_master_init) — a real
		 * M-200 does not start granting the tick after ENROLL. -> ESTABLISHED only
		 * on the box's unicast/config accept (reac_master_rx): the box switches to
		 * unicast the instant it sees the grant, so it locks off even a partial
		 * burst. No forward timer — window expiry with no accept falls BACK to
		 * PROBING (anti-#130); the box's JOIN retry grid re-opens it. */
		if (m->grant_ticks == 0) {
			emit = REAC_M_EMIT_ENROLL;   /* the pre-grant arm frame, once */
		} else if (m->grant_ticks <= m->grant_dwell) {
			/* The dwell. With REACPW_ANNOUNCE_UNGRANTED (default ON) we HOLD the
			 * RECOGNIZED-BUT-UNGRANTED cfea (box width set, count=0 — stamped by
			 * enter_granting) on the wire at the free-running ~1/s announce cadence,
			 * FILLER between: a real M-200 keeps announcing this window through the
			 * whole ENROLL->grant hold. reac-pw used to emit hard FILLER here, so the
			 * cfea NEVER reached the wire during the dwell (announce-slot STARVATION)
			 * and the anchor input never saw the ungranted state. With the flag OFF
			 * this stays hard FILLER (prior behaviour, byte-unchanged). Repeated box
			 * cold-connect bursts land here too (reac_master_rx's same-box GRANTING
			 * guard keeps them from restarting the dwell). */
			if (announce_ungranted_enabled() && ++m->announce_tick >= m->fps) {
				m->announce_tick = 0;
				emit = REAC_M_EMIT_ANNOUNCE;
			} else {
				emit = REAC_M_EMIT_FILLER;
			}
		} else {
			int gt = m->grant_ticks - 1 - m->grant_dwell; /* burst timeline starts after enroll+dwell */
			if (gt % m->grant_stride == 0) {
				int k = gt / m->grant_stride;
				if (k < m->grant_burst_len) {
					emit = REAC_M_EMIT_GRANT;   /* an actual grant slot — NEVER displaced */
					idx = k;
				}
			}
			/* Every NON-grant burst slot would emit hard FILLER. With
			 * REACPW_ANNOUNCE_BURST (default OFF) convert those FILLER slots to the
			 * cfea announce on the free-running ~1/s announce_tick, so the count=0
			 * RECOGNIZED-BUT-UNGRANTED window (held in announce_blk by enter_granting)
			 * keeps reaching the wire THROUGHOUT the burst — extending the dwell-only
			 * ungranted window across the whole grant sweep to give the box a
			 * prolonged signal to escalate. announce_tick free-runs on EVERY burst slot
			 * (so the ~1/s cadence stays true across the burst), but ANNOUNCE is emitted
			 * only when it wraps AND this slot is not a GRANT slot — a wrap landing on a
			 * GRANT slot holds the tick and defers to the next FILLER slot, so GRANT/
			 * ENROLL delivery is byte-identical and the full sweep is still delivered.
			 * Only meaningful with REACPW_ANNOUNCE_UNGRANTED also on (announce_blk must
			 * hold count=0). With the flag OFF the guard short-circuits BEFORE
			 * ++announce_tick, so this branch is fully inert and the burst is byte-
			 * identical to today. */
			if (announce_burst_enabled() && ++m->announce_tick >= m->fps &&
			    emit != REAC_M_EMIT_GRANT) {
				m->announce_tick = 0;
				emit = REAC_M_EMIT_ANNOUNCE;
			}
		}
		m->grant_ticks++;
		/* Once the FULL enroll + 32-block burst is delivered, COMMIT to ESTABLISHED
		 * and hold — do NOT wait for a post-burst box unicast. The box goes quiet
		 * after the grant, waiting for the master to settle into the locked cadence;
		 * a master that instead times back to PROBING makes the box re-attempt
		 * forever (rig 2026-07-12: 27 grant-timeouts, box LED blinking faster, never
		 * stabilising). GRANTING is only entered on a validated box frame, so this is
		 * not "granting into silence"; the ~6.5 s link-check budget in ESTABLISHED
		 * drops back to PROBING if the box is genuinely gone (anti-#130 preserved as
		 * a BACKWARD safety, just not a forward-blocking gate). */
		if (m->grant_ticks >= m->grant_dwell + m->grant_burst_len * m->grant_stride + 1)
			enter_established(m);
		break;

	case REAC_M_ESTABLISHED:
		/* Linked: the SAME continuous control cadence as PROBING. HOLD: the
		 * 600-frame budget counts down every slot; every box RX event reloads
		 * it (reac_master_rx). */
		emit = control_cadence(m, &idx);
		if (--m->link_check <= 0) {
			m->drop_reason = REAC_M_DROP_PEER_GONE;
			enter_probing(m);
		}
		break;
	}

	/* Build this slot's probe (current phase + link-state sub) and publish its
	 * checksum as the FILLER descriptor, then advance the rotation. Must run
	 * BEFORE reac_master_stamp reads m->probe_blk / m->filler_desc. */
	if (emit == REAC_M_EMIT_PROBE)
		probe_prepare(m);

	if (tmpl_idx)
		*tmpl_idx = idx;
	return emit;
}

/* Overwrite type [16:18] + control block [18:50] of `frame` with `blk` (a 34-byte
 * [type|block] template), then re-apply the cdea/cfea checksum at [49]. The audio,
 * counter and C2/EA tail that reac_tx_build wrote are untouched. */
#define REAC_TYPE_OFF 16   /* type [16:18], control block [18:50] follows */

static void apply_block(uint8_t *frame, const uint8_t blk[34])
{
	memcpy(frame + REAC_TYPE_OFF, blk, 34); /* [16:50] = type[2] + block[32] */
	reac_ctrl_checksum_apply(frame);        /* re-stamp the checksum at [49]  */
}

/* The downstream FILLER control-block descriptor. A real master never leaves
 * [18:50] all-zero on a FILLER frame: it repeats the 2-byte pair "00 xx" 16x.
 *
 * SOLVED 2026-07-11 (live M-200 + S-1608 on the rig, #130). `xx` is NOT telemetry
 * and NOT a per-console constant — it is the CHECKSUM OF THE CURRENT PROBE. The
 * probe rotates (gen_probe), and every FILLER emitted until the next probe carries
 * that probe's checksum, byte-verified on the wire:
 *
 *   P:de P:de  F:de x16   P:dd P:dd  F:dd x16   P:dc P:dc  F:dc x10  ...
 *
 * An earlier RE pass mistook the resulting cycle for "a live analog telemetry
 * sample (PLL-jitter / ADC noise-floor readback), UNLIKELY to be handshake-load-
 * bearing" — that reading was WRONG, and it hid the real defect: because our probe
 * was frozen, our descriptor was frozen too (a constant 0xdc), so our downstream
 * never presented the rotating hunt state a box expects.
 *
 * FILLER stays checksum-exempt: [49] here is descriptor data, not a checksum. */
static void stamp_filler_descriptor(uint8_t *frame, uint8_t desc)
{
	for (int i = REAC_CTRL_BLOCK_OFF; i < REAC_CTRL_BLOCK_END; i += 2) {
		frame[i] = 0x00;
		frame[i + 1] = desc;
	}
}

int reac_master_stamp(const struct reac_master *m, uint8_t *frame,
                      enum reac_master_emit emit, int tmpl_idx)
{
	switch (emit) {
	case REAC_M_EMIT_FILLER:
		/* reac_tx_build (or the pacer's silent-underrun filler) already wrote
		 * type 00 00 + audio + tail; stamp 16x "00 <current-probe-checksum>",
		 * which is exactly what a real master repeats there (#130). */
		stamp_filler_descriptor(frame, m->filler_desc);
		return 0;
	case REAC_M_EMIT_PROBE:
		apply_block(frame, m->probe_blk); /* the ROTATING probe (probe_prepare) */
		return 0;
	case REAC_M_EMIT_SUB01:
		apply_block(frame, SUB01_BLK);   /* the fixed M-300 cdea 01 01 */
		return 0;
	case REAC_M_EMIT_SUB02:
		apply_block(frame, SUB02_BLK);   /* the fixed M-300 cdea 01 02 */
		return 0;
	case REAC_M_EMIT_GRANT:
		/* One block of the GENERATED enrollment sweep (reac_grant_build_sweep over
		 * our own allocation for this box); tmpl_idx is the burst position set by
		 * reac_master_next. Group-A rows come from the proven head-amp builder and
		 * the fixed head/group-B rows already sum to 0 over [18:50], so apply_block's
		 * re-checksum is a no-op — the on-wire bytes equal a real M-200's. */
		if (tmpl_idx < 0 || tmpl_idx >= m->grant_burst_len)
			return -1;
		apply_block(frame, m->grant_burst[tmpl_idx]);
		return 0;
	case REAC_M_EMIT_ENROLL:
		apply_block(frame, m->enroll_blk);  /* cdea 01 03 000d, per-mixer console byte */
		return 0;
	case REAC_M_EMIT_CHANMAP:
		if (tmpl_idx < 0 || tmpl_idx >= m->chanmap_nframes)
			return -1;
		apply_block(frame, m->chanmap[tmpl_idx]);
		return 0;
	case REAC_M_EMIT_ANNOUNCE:
		apply_block(frame, m->announce_blk);
		return 0;
	}
	return -1;
}
